apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeromq-client2-deployment
spec:
  selector:
    matchLabels:
      app: zeromq
  replicas: 1
  template:
    metadata:
      labels:
        app: zeromq
    spec:
      containers:
      - name: zeromq-client2
        image: registry.hub.docker.com/alaasalmo/zeromq-client2:v2
        volumeMounts:
        - mountPath: /logs
          name: zvolume
      volumes:
      - name: zvolume
        persistentVolumeClaim:
          claimName: zeromq-pvc